const actionTypes = {
  SIGIN_IN: "SIGNININ",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  SIGN_UP: "SIGNUP",
  RESET_SIGNUP: "RESET_SIGNUP",
  LOGOUT: "LOGOUT",
  ERROR: "ERROR",
  HOME_DATA: "HOME_DATA",
  ALL_GENRES: "ALL_GENRES",
  MOVIE_DETAILS: "MOVIE_DETAILS",
  ALL_MOVIES_OF_GENRE: "ALL_MOVIES_OF_GENRE",
  USER_DETAILS: "USER_DETAILS"
};

module.exports = actionTypes;
