const CONSTANTS = {
  SUCCESS: 200,
  INTERNAL_SERVER_ERROR_CODE: 500,
  BAD_REQUEST_CODE: 400,
  FETCH_ALL_SOURCES: "FETCH_ALL_SOURCES",
  API_VERSION: "/api/v1",
  PAGE_SIZE: 5,
  ACCESS_TOKEN_EXPIRED: "accessTokenExpired",
  FORBIDDEN: 403,
  UN_AUTHORIZED: 401,
};

module.exports = CONSTANTS;
