const CONSTANTS = {
  ERROR: "error",
  SUCCESS: "success",
  INTERNAL_SERVER_ERROR_CODE: 500,
  BAD_REQUEST_CODE: 400,
  FETCH_ALL_SOURCES: "FETCH_ALL_SOURCES",
  API_VERSION: '/api/v1',
  PAGE_SIZE: 5
};

module.exports = CONSTANTS;
